'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BondRate
  'Public Property ID As Integer
  'Public Property ReportID As Integer
  'Public Property Symbol As String
  'Public Property Name As String
  'Public Property Type As Short 'Short is an int16
  'Public Property Security As Short
  'Public Property Interest As Single
  'Public Property MaturityDays As Integer
  'Public Property DateUpdate As Date

  'Public Overridable Property Report As Report

End Class
