'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FinancialHighlight
  'Public Property ID As Integer
  'Public Property BookValuePerShare As Single
  'Public Property CurrentRatio As Single
  'Public Property DilutedEPS As Single
  'Public Property EBITDAInMillion As Single
  'Public Property FiscalYearEnds As Date
  'Public Property GrossProfitInMillion As Single
  'Public Property LeveredFreeCashFlowInMillion As Single
  'Public Property MostRecentQuarter As Date
  'Public Property NetIncomeAvlToCommonInMillion As Single
  'Public Property OperatingCashFlowInMillion As Single
  'Public Property OperatingMarginPercent As Single
  'Public Property ProfitMarginPercent As Single
  'Public Property QuarterlyRevenueGrowthPercent As Single
  'Public Property QuaterlyEarningsGrowthPercent As Single
  'Public Property ReturnOnAssetsPercent As Single
  'Public Property ReturnOnEquityPercent As Single
  'Public Property RevenueInMillion As Single
  'Public Property RevenuePerShare As Single
  'Public Property TotalCashInMillion As Single
  'Public Property TotalCashPerShare As Single
  'Public Property TotalDeptInMillion As Single
  'Public Property TotalDeptPerEquity As Single
  'Public Property RecordID As Integer
  'Public Property DateUpdate As Date

  'Public Overridable Property Record As Record

End Class
