'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MarketQuoteData
  'Public Property ID As Integer
  'Public Property DividendYieldPercent As Single
  'Public Property LongTermDeptToEquity As Single
  'Public Property MarketCapitalizationInMillion As Single
  'Public Property NetProfitMarginPercent As Single
  'Public Property PriceEarningsRatio As Single
  'Public Property PriceToBookValue As Single
  'Public Property PriceToFreeCashFlow As Single
  'Public Property ReturnOnEquityPercent As Single
  'Public Property RecordID As Integer
  'Public Property DateUpdate As Date

  'Public Overridable Property Record As Record

End Class
