'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QuoteValue
  'Public Property ID As Integer
  'Public Property AfterHoursChangeRealtime As Single
  'Public Property AnnualizedGain As Single
  'Public Property Ask As Single
  'Public Property AskRealTime As Single
  'Public Property AskSize As Integer
  'Public Property AverageDailyVolume As Integer
  'Public Property Bid As Single
  'Public Property BidRealtime As Single
  'Public Property BidSize As Integer
  'Public Property BookValue As Single
  'Public Property DividendPayDate As Date
  'Public Property DividendShare As Single
  'Public Property DividendYield As Single
  'Public Property EarningsShare As Single
  'Public Property EBITDA As Single
  'Public Property EPSEstimateCurrentYear As Single
  'Public Property EPSEstimateNextQuarter As Single
  'Public Property EPSEstimateNextYear As Single
  'Public Property ExDividendDate As Date
  'Public Property FloatShares As Integer
  'Public Property HoldingsValue As Single
  'Public Property HoldingsValueRealtime As Single
  'Public Property LastTradeDate As Date
  'Public Property LastTradePriceOnly As Single
  'Public Property LastTradeRealtimeWithTime As Date
  'Public Property LastTradeSize As Integer
  'Public Property MarketCapitalization As Single
  'Public Property MarketCapRealtime As Single
  'Public Property OneyrTargetPrice As Single
  'Public Property OrderBookRealtime As Single
  'Public Property PEGRatio As Single
  'Public Property PERatio As Single
  'Public Property PERatioRealtime As Single
  'Public Property PriceBook As Single
  'Public Property PriceEPSEstimateCurrentYear As Single
  'Public Property PriceEPSEstimateNextYear As Single
  'Public Property PriceSales As Single
  'Public Property SharesOwned As Integer
  'Public Property ShortRatio As Single
  'Public Property TickerTrend As Single
  'Public Property RecordID As Integer
  'Public Property StockExchange As String
  'Public Property DateUpdate As Date

  'Public Overridable Property Record As Record

End Class
