'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Record
  'Public Property ID As Integer
  'Public Property StockID As Integer
  'Public Property DateDay As Date
  'Public Property DateUpdate As Date
  'Public Property DateLastTrade As Date
  'Public Property Open As Single
  'Public Property Last As Single
  'Public Property High As Single
  'Public Property Low As Single
  'Public Property Vol As Integer

  'Public Overridable Property FinancialHighlights As ICollection(Of FinancialHighlight) = New HashSet(Of FinancialHighlight)
  'Public Overridable Property MarketQuoteDatas As ICollection(Of MarketQuoteData) = New HashSet(Of MarketQuoteData)
  'Public Overridable Property QuoteValues As ICollection(Of QuoteValue) = New HashSet(Of QuoteValue)
  'Public Overridable Property TradeInfoes As ICollection(Of TradeInfo) = New HashSet(Of TradeInfo)
  'Public Overridable Property ValuationMeasures As ICollection(Of ValuationMeasure) = New HashSet(Of ValuationMeasure)
  'Public Overridable Property Stock As Stock

End Class
