'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Report
  'Public Property ID As Integer
  'Public Property Name As String = ""
  'Public Property DateStart As Date
  'Public Property DateStop As Date

  'Public Overridable Property Industries As ICollection(Of Industry) = New HashSet(Of Industry)
  'Public Overridable Property Sectors As ICollection(Of Sector) = New HashSet(Of Sector)
  'Public Overridable Property Stocks As ICollection(Of Stock) = New HashSet(Of Stock)
  'Public Overridable Property SplitFactorFutures As ICollection(Of SplitFactorFuture) = New HashSet(Of SplitFactorFuture)
  'Public Overridable Property BondRates As ICollection(Of BondRate) = New HashSet(Of BondRate)

End Class
