'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sector
  'Public Property ID As Integer
  'Public Property Name As String
  'Public Property ReportID As Integer
  'Public Property DataSourceID As Integer

  'Public Overridable Property Industries As ICollection(Of Industry) = New HashSet(Of Industry)
  'Public Overridable Property Report As Report
  'Public Overridable Property Stocks As ICollection(Of Stock) = New HashSet(Of Stock)

End Class
