'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SplitFactorFuture
  'Public Property ID As Integer
  'Public Property ReportID As Integer
  'Public Property Symbol As String
  'Public Property Name As String
  'Public Property DateAnnounce As Nullable(Of Date)
  'Public Property DatePayable As Nullable(Of Date)
  'Public Property Exchange As String
  'Public Property DateEx As Date
  'Public Property SharesLast As Integer
  'Public Property SharesNew As Integer
  'Public Property Ratio As Single
  'Public Property DateUpdate As Nullable(Of Date)

  'Public Overridable Property Report As Report

End Class
