'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SplitFactor
  'Public Property ID As Integer
  'Public Property StockID As Integer
  'Public Property DateDay As Date
  'Public Property SharesLast As Integer
  'Public Property SharesNew As Integer
  'Public Property Ratio As Single

  'Public Overridable Property Stock As Stock

End Class
