'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StockSymbol
  'Public Property ID As Integer
  'Public Property DateUpdate As Date
  'Public Property Exchange As String
  'Public Property Name As String
  'Public Property IndustryID As Integer
  'Public Property SectorID As Integer
  'Public Property Symbol As String
  'Public Property SymbolNew As String
  'Public Property StockID As Integer

  'Public Overridable Property Stock As Stock

End Class
