'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Stock
  '  Public Property ID As Integer
  '  Public Property Symbol As String
  '  Public Property Name As String
  '  Public Property IndustryID As Integer
  '  Public Property SectorID As Integer
  '  Public Property IsOption As Boolean
  '  Public Property DateStart As Date
  '  Public Property DateStop As Date
  '  Public Property IsSymbolError As Boolean
  '  Public Property ReportID As Integer
  '  Public Property Exchange As String
  '  Public Property ErrorDescription As String

  '  Public Overridable Property Industry As Industry
  ''Public Overridable Property Records As ICollection(Of Record) = New HashSet(Of Record)
  '  Public Overridable Property Report As Report
  '  Public Overridable Property Sector As Sector
  ''Public Overridable Property SplitFactors As ICollection(Of SplitFactor) = New HashSet(Of SplitFactor)
  ''Public Overridable Property StockErrors As ICollection(Of StockError) = New HashSet(Of StockError)
  ''Public Overridable Property StockSymbols As ICollection(Of StockSymbol) = New HashSet(Of StockSymbol)

End Class
