'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class StockYahooEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=StockYahooEntities")
        MyBase.Configuration.LazyLoadingEnabled = False
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
	    Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property FinancialHighlights() As DbSet(Of FinancialHighlight)
    Public Property Industries() As DbSet(Of Industry)
    Public Property MarketQuoteDatas() As DbSet(Of MarketQuoteData)
    Public Property QuoteValues() As DbSet(Of QuoteValue)
    Public Property Records() As DbSet(Of Record)
    Public Property Reports() As DbSet(Of Report)
    Public Property Sectors() As DbSet(Of Sector)
    Public Property SplitFactors() As DbSet(Of SplitFactor)
    Public Property Stocks() As DbSet(Of Stock)
    Public Property TradeInfoes() As DbSet(Of TradeInfo)
    Public Property ValuationMeasures() As DbSet(Of ValuationMeasure)
    Public Property SplitFactorFutures() As DbSet(Of SplitFactorFuture)
    Public Property BondRates() As DbSet(Of BondRate)
    Public Property StockSymbols() As DbSet(Of StockSymbol)
    Public Property StockErrors() As DbSet(Of StockError)

End Class
