'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TradeInfo
  'Public Property ID As Integer
  'Public Property AverageVolumeTenDaysInThousand As Single
  'Public Property AverageVolumeThreeMonthInThousand As Single
  'Public Property Beta As Single
  'Public Property DividendDate As Date
  'Public Property ExDividendDate As Date
  'Public Property FiftyDayMovingAverage As Single
  'Public Property FiveYearAverageDividendYieldPercent As Single
  'Public Property FloatInMillion As Single
  'Public Property ForwardAnnualDividendRate As Single
  'Public Property ForwardAnnualDividendYieldPercent As Single
  'Public Property LastSplitDate As Date
  'Public Property LastSplitFactor As Date
  'Public Property OneYearChangePercent As Single
  'Public Property OneYearHigh As Single
  'Public Property OneYearLow As Single
  'Public Property PayoutRatio As Single
  'Public Property PercentHeldByInsiders As Single
  'Public Property PercentHeldByInstitutions As Single
  'Public Property SharesOutstandingInMillion As Single
  'Public Property SharesShortInMillion As Single
  'Public Property SharesShortPriorMonthInMillion As Single
  'Public Property ShortPercentOfFloat As Single
  'Public Property ShortRatio As Single
  'Public Property TrailingAnnualDividendYield As Single
  'Public Property TrailingAnnualDividendYieldPercent As Single
  'Public Property TwoHundredDayMovingAverage As Single
  'Public Property RecordID As Integer
  'Public Property DateUpdate As Date

  'Public Overridable Property Record As Record

End Class
