'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ValuationMeasure
  'Public Property ID As Integer
  'Public Property EnterpriseValueInMillion As Single
  'Public Property EnterpriseValueToEBITDA As Single
  'Public Property EnterpriseValueToRevenue As Single
  'Public Property ForwardPE As Single
  'Public Property MarketCapitalisationInMillion As Single
  'Public Property PEGRatio As Single
  'Public Property PriceToBook As Single
  'Public Property PriceToSales As Single
  'Public Property TrailingPE As Single
  'Public Property RecordID As Integer
  'Public Property DateUpdate As Date

  'Public Overridable Property Record As Record

End Class
